### ISSUE TITLE
关于文中其中一点 androidstudio 换字体 怎么换的呢

### ISSUE THREAD

**Issue by dicallc** [cctanfujun/android-tips-tricks-cn#5]
给你的 Android Studio 选择一个合适的字体，作者推荐使用Menlo font 反正我觉得mac的字体就挺好的，在linux上开发已经觉得不顺眼了.

在AS中没有看到Menlo  字体

**Comment by cctanfujun** [comment]
给你的系统装上这个字体应该就有了吧 我这有啊
